language: ruby
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
services:
  - postgres
